// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzWI_q1I7JbWyvDcBPSjlnxG_aM8lsM88',
    appId: '1:595857336811:web:6cd84831ab6ab8ae09d1ae',
    messagingSenderId: '595857336811',
    projectId: 'event-planner-6b8bd',
    authDomain: 'event-planner-6b8bd.firebaseapp.com',
    storageBucket: 'event-planner-6b8bd.firebasestorage.app',
    measurementId: 'G-29ST4B28M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBMCnLObpMvv77y5AR2ZqxRTu4ruPuDZ8',
    appId: '1:595857336811:android:15ee6e85bbaf410909d1ae',
    messagingSenderId: '595857336811',
    projectId: 'event-planner-6b8bd',
    storageBucket: 'event-planner-6b8bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkiaTgnljLbU02cHKKsszdGI9-Uv0Wn5c',
    appId: '1:595857336811:ios:61d7d96ea4120aea09d1ae',
    messagingSenderId: '595857336811',
    projectId: 'event-planner-6b8bd',
    storageBucket: 'event-planner-6b8bd.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkiaTgnljLbU02cHKKsszdGI9-Uv0Wn5c',
    appId: '1:595857336811:ios:61d7d96ea4120aea09d1ae',
    messagingSenderId: '595857336811',
    projectId: 'event-planner-6b8bd',
    storageBucket: 'event-planner-6b8bd.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzWI_q1I7JbWyvDcBPSjlnxG_aM8lsM88',
    appId: '1:595857336811:web:b7046930c5f2e98509d1ae',
    messagingSenderId: '595857336811',
    projectId: 'event-planner-6b8bd',
    authDomain: 'event-planner-6b8bd.firebaseapp.com',
    storageBucket: 'event-planner-6b8bd.firebasestorage.app',
    measurementId: 'G-HFGXFGZGZK',
  );
}
